apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd  # Assuming Argo CD is installed in the 'argocd' namespace
spec:
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

